### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by volodymyr-kushnir** [RAYDENFilipp/Git-homework#1]
Hey, @RAYDENFilipp, congrats on your first commit. Care to create a project for yourself in the [**Projects**](https://github.com/RAYDENFilipp/Git-homework/projects) section? Not mandatory, but recommended.

**Comment by RAYDENFilipp** [comment]
@volodymyr-kushnir
Hello!
Thanks, I did it. But it seems I don't know what to do with that project. I'm also confused about the deadline, whether it's May 22d or 21st. The email and BSA profile page information differs.

**Comment by volodymyr-kushnir** [comment]
@RAYDENFilipp I'm not sure about the deadline. I just gave a lecture and now I'm checking how it's going on for you guys. But AFAIK it's May 21st 23:59.
As for the project, how about this tasks:

* change *.txt to *.md
* give names to your articles (*First-text* doesn't tell much)
* add README.md with short description of your repository
* add links to the articles to the README.md

All those can be separate cards, you can move cards to the **In progress** column when you start working on them, and move them to the **Done** when you finished. Separate cards mean separate issues — you can convert them to issues straight from the **Projects** section on GitHub — they have an option in the  menu for that. When you finish the task you also close the issue. That's sort of how agile development works.

**Comment by RAYDENFilipp** [comment]
@volodymyr-kushnir 
I've completed the tasks you gave to me.
Did I understand you correct and those are what you meant?

**Comment by volodymyr-kushnir** [comment]
@RAYDENFilipp, так, порядок. Перейшов на українську, бо це вже мій напевно 100 комент за сьогодні, треба трохи з'їхати з англійської. Все в порядку, єдине, що важливо зрозуміти (раз ми вже тут, бо до завдання то відношення не має) — agile development.
Зазвичай робляться 4 колонки — **Backlog**, **Ready**, **In progress**, **Done**.
В **Backlog** йдуть всі описи проблем, якщо картка не блокована іншим завданням, то вона переміщується в **Ready**, тоді в **In progress**, тоді в **Done**. На кожному етапі менеджер може побачити повну картинку — що робиться, що зроблено, що блоковано, що ще треба зробити.

До кожної картки в **Project** має бути мінімум одна проблема в **Issues**. Картки в **Project** для менеджера, проблеми в **Issues** для розробника. Наприклад, картка "Зробити няшно" може мати проблеми "Покрасити фон чорним" і "Покрасити текст білим", і над проблемами можуть працювати різні люди в різних гілках. Тоді ті проблеми закриваються, таска падає в **Done** і _they lived happily ever after_.

**Comment by RAYDENFilipp** [comment]
@volodymyr-kushnir 
Ага...То я дороблю необхідні колонки(щоб було) і відправлю на перевірку через свій кабінет. Але це все, гадаю, буде більш зрозумілим, коли доведеться користуватися всим цим регулярно на практиці.
Бо на даному етапі це все як "Сферичний конь у вакуумі" )))

**Comment by volodymyr-kushnir** [comment]
@RAYDENFilipp гаразд, звичайно

**Comment by RAYDENFilipp** [comment]
@volodymyr-kushnir 
Виникло одне питання.
Я так помітив, що як я закрию  гілки, що вже об'єднані то вони з історії наче пропадають. Чи маю я їх залишити?

**Comment by volodymyr-kushnir** [comment]
![image](https://cloud.githubusercontent.com/assets/10290626/26279340/979d7c46-3db9-11e7-906c-3b3438d28911.png)
Це так, пропадають і це окей, бо вони більше не треба, адже всі зміни вже залиті в іншу гілку. Той самий **GitKraken** прекрасно показує шо **patch-1** існував свого часу, але був зшитий до **develop**.

**Comment by RAYDENFilipp** [comment]
@volodymyr-kushnir 
Дякую :+1:
